name: CI workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #
      #      - name: Set up Python
      #        uses: actions/setup-python@v2
      #        with:
      #          python-version: "3.0"
      #
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #
      - name: Linting
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
          echo "Linting step"

      - name: Run tests
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
          echo "Testing step"
